name: Build

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.action_path }}
  cancel-in-progress: true

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: termux/upload-release-action@v4.0.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mything
        asset_name: mything
        tag: "test"
        overwrite: true
        body: "This is my release text"
        checksums: sha256,sha512,md5
